### ISSUE TITLE
"No file named mix" error with default settings on Windows

### ISSUE THREAD

**Issue by indyone** [rgreenjr/atom-elixir-formatter#10]
When using `atom-elixir-formatter` on Windows to format an Elixir document with the default settings for the **Elixir Executable** & **Mix Executable** you get the error as seen in the screenshot below:

![capture](https://user-images.githubusercontent.com/1120410/32511195-b6ec6210-c3fb-11e7-9ba6-4d888edb22cb.PNG)

After an investigation I did, the problem is that on windows the command that is produced with the default settings is:
```
cmd.exe elixir mix format -
```
When the command is executed, `elixir` is expanded to the the first `elixir.bat` found in the `PATH` environment variable, but `mix` is not. This results to `elixir.bat` try to find a file named `mix` in the current directory, which does not exists, and returns this error.

---
At the moment, as a workaround for Windows users, is to set the **Elixir Executable** & **Mix Executable** to the absolute paths of the `bin\elixir` & `bin\mix`. Eg.

![capture](https://user-images.githubusercontent.com/1120410/32511732-5577e0de-c3fd-11e7-889f-870ed763a572.PNG)

~~Please note, as of the issue #9 it is needed to add the path in double quotes if it has spaces.~~
Upd: If your path contain spaces, make sure you have >v0.2.6.

**Comment by thiagogsr** [comment]
Same on OSX

**Comment by rgreenjr** [comment]
@indyone Issue #9 should be fixed in version 0.2.4. Please give it a try and let me know if it works for you on Windows. Thanks!

**Comment by rgreenjr** [comment]
Hi @thiagogsr, Did you download and compile the master branch of Elixir and then set the `atom-elixir-formatter` settings for **Elixir Executable** and **Mix Executable** to the absolute paths of the `elixir` and `mix` executables?

**Comment by thiagogsr** [comment]
Hi @rgreenjr my bad, it works after change the path of mix and elixir. Thanks

**Comment by rgreenjr** [comment]
@thiagogsr – No problem, glad it's working for you. 👍

**Comment by indyone** [comment]
@rgreenjr, i was working on replacing the **Elixir Executable** and **Mix Executable** with **Elixir Path** setting (as i suggested in my comment in PR #7). This solution fixes issues Windows, works on other OS too and has only one setting for both executables!

Please check it in my fork 80b243b and tell me what do you think.
Thanks

**Comment by rgreenjr** [comment]
@indyone I've been out of town but will be back tomorrow. I'll make sure to find time to look at your work then. Thanks!

**Comment by rgreenjr** [comment]
I finally had time to look at your work today and I like the direction. I agree that we don't need both **Elixir Executable** and **Mix Executable** settings. 

I also agree that the default  command should be `mix format -` to minimize the need for configuration once Elixir v1.6 is released.

I'd prefer, however, to keep the **Elixir Executable** setting and only eliminate **Mix Executable**. Then the logic would be:

- If **Elixir Executable** is unset, run `mix format -`
- If **Elixir Executable** is set, run `/absolute/path/to/elixir /absolute/path/to/mix format -`

It feels more logical (at least to me) to have users specify an `elixir` executable path instead of a `bin` path. Ultimately, it amounts to the same things, but this feels more consistent. The `dirname` of the **Elixir Executable** setting will be used for `mix` path.

Thoughts?

**Comment by rgreenjr** [comment]
@indyone I've pulled down several of your changes and I'm preparing a release that should resolve this issue soon.

**Comment by rgreenjr** [comment]
@indyone Release 0.3.0 is out now. Please give it a try and let me know if you run into any issues on Windows. Hopefully we can close this issue. Thanks.  👍

**Comment by indyone** [comment]
Hi @rgreenjr, sorry that I didn't help you with updating the code, so that it works with the `Elixir Executable` setting only as you suggested, but i reviewed the code you committed and it's indeed a very good solution!
I tested it on Windows and finally it works perfectly, with a custom path or by using the default value! 👍 
Thanks a lot.

**Comment by rgreenjr** [comment]
@indyone Thank you too! I'm very glad everything is working on Windows now.
